---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-home-assistant
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-emqx
    # - name: cluster-apps-cloudnative-pg-cluster
    - name: cluster-apps-onepassword-connect
    - name: cluster-apps-democratic-csi-freenas-nfs
  path: ./kubernetes/apps/default/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: home-assistant
      namespace: default
  interval: 30m
  retryInterval: 1m
  timeout: 3m
