---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1lqqpw0p96tex8gfg0m45l99jz9307qke8ajctevrthdxsaknm38qyeq33f
  - path_regex: ansible/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1lqqpw0p96tex8gfg0m45l99jz9307qke8ajctevrthdxsaknm38qyeq33f
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1lqqpw0p96tex8gfg0m45l99jz9307qke8ajctevrthdxsaknm38qyeq33f
