---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./external-dns.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jetstack.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
  - ./external-secrets.yaml
  - ./democratic-csi.yaml
  - ./emqx.yaml
  - ./cloudnative-pg.yaml
  - ./grafana.yaml
  - ./prometheus-community.yaml
  - ./kyverno.yaml
  - ./backube.yaml
  - ./piraeus.yaml
  - ./crunchydata.yaml
