---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-crunchydata
  namespace: flux-system
spec:
  path: ./kubernetes/apps/default/crunchydata/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: crunchydata
      namespace: default
  interval: 15m
  retryInterval: 1m
  timeout: 3m
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: cluster-apps-crunchydata-cluster
#   namespace: flux-system
# spec:
#   dependsOn:
#     - name: cluster-apps-crunchydata
#     - name: cluster-apps-democratic-csi-freenas-iscsi
#     - name: cluster-apps-onepassword-connect
#     - name: cluster-apps-minio
#   path: ./kubernetes/apps/default/crunchydata/cluster
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: home-kubernetes
#   wait: true
#   interval: 15m
#   retryInterval: 1m
#   timeout: 3m
