---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: crunchydata
  namespace: flux-system
spec:
  interval: 2h
  url: oci://registry.developers.crunchydata.com/crunchydata/pgo
  ref:
    tag: 5.3.1
