apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/NBYYa9EAKhcdE2QtJ1olFQeqfbcgYuHLw6SbRH5Yc7BFz9jY10D4Q==,iv:DnDMeZND1vheobfE912H35sRsNRwy/M/LRWraFooWxA=,tag:Z+t/bp2tP5+F3xGFcKIKSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1lqqpw0p96tex8gfg0m45l99jz9307qke8ajctevrthdxsaknm38qyeq33f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdGFDTU8rMzVKYTU5T0V1
            RnR1QVRnczUzVWRDNXZYOGM5b01xcGRXSXdzCnpOdFNWUVozRUc4MHB0NWFua3d5
            Uk1Bc0J4eUlXSmRvYTcvakVqNURJcjQKLS0tIGpOVkJ0ZnNLdit4NWl6ZGVvWXNn
            LzFBTzZBZzlRd0t4bWZXYmpFb0F4Zm8KV7TSanIKY/v81GSHki5iEOloYA2NV64G
            qZtUaqppCcvnDAHF55H6m+udNEGWgDhT5nKkFJ0hPREF6eHw18jOMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-28T19:29:32Z"
    mac: ENC[AES256_GCM,data:6B5OBetCmm6JkKggzS3mXxKdKhnt2UrCp5SulKAL5QiU68m4AnILosRf9nc/uNdEH+YTM18AyXgwxLHUwnk03A839z37F0MgZHi/xx45jh59mbdxnZYdFAvwYJYv7AS/0T2e6f8A9X8wcbTJ3vd5tZI/e5hqIFV5JsJtt1aR6Ic=,iv:5eOY7dGOHW+oEEVrTmzpbMWnO8KDJ1TjhT3CAHw3G0Y=,tag:5inbWLIRvaQqVdQdaowPgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
