---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx
      version: 5.0.24
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 3
    recreatePods: true
    emqxConfig:
      ALLOW_ANONYMOUS: "false"
      AUTH__MNESIA__PASSWORD_HASH: plain
    service:
      type: LoadBalancer
      externalIPs: ["${SVC_EMQX_ADDR}"]
      externalTrafficPolicy: Local
    ingress:
      dashboard:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/appName: "EMQX"
          hajimari.io/icon: simple-icons:eclipsemosquitto
          nginx.ingress.kubernetes.io/affinity: "cookie"
          nginx.ingress.kubernetes.io/session-cookie-name: "stickounet"
          nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
          nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
        path: /
        pathType: Prefix
        hosts:
          - &host emqx.${SECRET_DOMAIN}
        tls:
          - hosts:
              - *host
            secretName: emqx-tls
    metrics:
      enabled: false
    persistence:
      enabled: true
      existingClaim: emqx-config
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values: ["emqx"]
              topologyKey: kubernetes.io/hostname
  valuesFrom:
    - targetPath: emqxConfig.EMQX_DASHBOARD__DEFAULT_PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: admin_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__1__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: user_1_password
    - targetPath: emqxConfig.EMQX_AUTH__USER__2__USERNAME
      kind: Secret
      name: emqx-secret
      valuesKey: user_2_username
    - targetPath: emqxConfig.EMQX_AUTH__USER__2__PASSWORD
      kind: Secret
      name: emqx-secret
      valuesKey: user_2_password
