---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx-operator
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: emqx-operator
      version: 2.1.1
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
