---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emqx-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: freenas-nfs-csi
  resources:
    requests:
      storage: 20Mi
