---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres
  namespace: default
spec:
  schedule: "@hourly"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: postgres
