---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: freenas-iscsi
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    csiDriver:
      name: "org.democratic-csi.iscsi"

    storageClasses:
      - name: freenas-iscsi-csi
        defaultClass: true
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: xfs

        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
          node-publish-secret:
          controller-expand-secret:

    volumeSnapshotClasses:
      - name: freenas-iscsi-csi
        parameters:
      # if true, snapshots will be created with zfs send/receive
        detachedSnapshots: "true"
        secrets:
          snapshotter-secret:

    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          protocol: http
          host: 10.100.1.240
          port: 80
          allowInsecure: true
          apiVersion: 2
        # sshConnection:
        #   host: 192.168.178.241
        #   port: 22
        zfs:
          # the example below is useful for TrueNAS 12
          cli:
            paths:
              zfs: /usr/local/sbin/zfs
              zpool: /usr/local/sbin/zpool
              sudo: /usr/local/bin/sudo
              chroot: /usr/sbin/chroot
          # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
          # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
          # standard volume naming overhead is 46 chars
          # datasetParentName should therefore be 17 chars or less
          datasetParentName: p/k3s/iscsi/vol
          detachedSnapshotsDatasetParentName: p/k3s/iscsi/snap
          # "" (inherit), lz4, gzip-9, etc
          zvolCompression:
          # "" (inherit), on, off, verify
          zvolDedup:
          zvolEnableReservation: false
          # 512, 1K, 2K, 4K, 8K, 16K, 64K, 128K default is 16K
          zvolBlocksize:
        iscsi:
          targetPortal: "10.100.1.240:3260"
          targetPortals: []
          # leave empty to omit usage of -I with iscsiadm
          interface:
          namePrefix: csi-
          nameSuffix: "-cluster"
          # add as many as needed
          targetGroups:
            # get the correct ID from the "portal" section in the UI
            - targetGroupPortalGroup: 1
              # get the correct ID from the "initiators" section in the UI
              targetGroupInitiatorGroup: 1
              # None, CHAP, or CHAP Mutual
              targetGroupAuthType: None
              # get the correct ID from the "Authorized Access" section of the UI
              # only required if using Chap
              targetGroupAuthGroup:
          extentInsecureTpc: true
          extentXenCompat: false
          extentDisablePhysicalBlocksize: true
          # 512, 1024, 2048, or 4096,
          extentBlocksize: 4096
          # "" (let FreeNAS decide, currently defaults to SSD), Unknown, SSD, 5400, 7200, 10000, 15000
          extentRpm: "SSD"
          # 0-100 (0 == ignore)
          extentAvailThreshold: 0
  valuesFrom:
    - targetPath: driver.config.httpConnection.apiKey
      kind: Secret
      name: democratic-csi-freenas-iscsi-secret
      valuesKey: api_key
    # - targetPath: driver.config.httpConnection.username
    #   kind: Secret
    #   name: democratic-csi-freenas-iscsi-secret
    #   valuesKey: api_user
    # - targetPath: driver.config.sshConnection.username
    #   kind: Secret
    #   name: democratic-csi-freenas-iscsi-secret
    #   valuesKey: ssh_user
    # - targetPath: driver.config.sshConnection.password
    #   kind: Secret
    #   name: democratic-csi-freenas-iscsi-secret
    #   valuesKey: ssh_password
