---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: disocrd-webhook
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: disocrd-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: address
      remoteRef:
        key: flux
        property: dicord_webhook
