---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: default
  annotations:
    kyverno.io/ignore: "true"
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-15.2-0
  postgresVersion: 15

  users:
    - name: home-assistant
      databases:
        - homeassistant

  instances:
    - name: cluster
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: freenas-iscsi-csi
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 64Gi

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.41-4
      configuration:
      - secret:
          name: postgres-secret
      global:
        repo1-path: /postgres/repo1
      repos:
      - name: repo1
        s3:
          bucket: "postgres"
          endpoint: "https://s3.mdegouw.nl"
          region: "nl-home"

  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.18-0
      replicas: 2
