---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  KUBE_VIP_ADDR: "10.69.126.20"
  METALLB_LB_RANGE: "10.69.126.120-10.69.126.129"
  METALLB_K8S_GATEWAY_ADDR: "10.69.126.120"
  METALLB_INGRESS_ADDR: "10.69.126.121"


  SVC_INGRESS_ADDR: "10.69.0.1"
  SVC_K8S_GATEWAY_ADDR: "10.69.0.2"
  SVC_EMQX_ADDR: "10.69.0.11"
  SVC_PG_ADDR: "10.69.0.12"
