---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant02
  namespace: default
spec:
  secretStoreRef:
    kind: SecretStore
    name: default
  target:
    name: home-assistant02-secret
    creationPolicy: Owner
  dataFrom:
  - find:
      name:
        regexp: "postgres-pguser-home-assistant"
