---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ./externalsecret.yaml
  - ./externalsecret02.yaml
  - ./helmrelease.yaml
  - ./volsync.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
