---
# yaml-language-server: $schema=https://frigate.bjw-s.dev/api/config/schema
logger:
  default: info
  # logs:
  #   frigate.record: debug

birdseye:
  enabled: false

# mqtt:
#   host: mosquitto.home-automation
#   port: 1883
#   topic_prefix: frigate
#   user: frigate
#   password: "{FRIGATE_MQTT_PASSWORD}"

database:
  path: /data/frigate.db

detectors:
  coral:
    type: edgetpu
    device: usb

# Global ffmpeg configuration
ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

# Global snapshots configuration
snapshots:
  enabled: true
  timestamp: false
  bounding_box: true
  retain:
    default: 14

# Global record configuration
record:
  enabled: true
  retain:
    days: 3
    mode: all
  events:
    retain:
      default: 14
      mode: active_objects

# Global objects configuration
objects:
  track:
    - person
  filters:
    person:
      min_area: 5000
      max_area: 100000
      threshold: 0.7

