---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esp-home
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/esphome/esphome
      tag: 2023.4.2@sha256:e1957bcf1b19783ffb11ec2af2eafd43060caa5a81e5d8f75bea16a1b61b472f
    env:
      ESPHOME_DASHBOARD_USE_PING: true
    service:
      main:
        ports:
          http:
            port: 6052
      hass:
        ports:
          http:
            port: 6053
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:home-assistant
        hosts:
          - host: &host esp-home.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        storageClass: freenas-nfs-csi
        type: pvc
        accessMode: ReadWriteOnce
        size: 1Gi
        mountPath: /config
        retain: true
